# Page settings
baseurl = "https://my-life-ua.gitlab.io"
title = "My Life"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "My Life"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Personal Lifestyle Monitoring System"
    subtitle = 'Be the best version of yourself with the help of our app. <br />Your health lifestyle will never be the same.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Nutrition"
    description = "We will use computer vision and a set of Machine Learning algorithms to recognise basic elements on a plate and to be able to tell important information like calories, macronutrients and others about the food the user is intaking."
    url = "#"
    # button = "Get In Touch"
    icon = "icon-apple"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Crossfit plan"
    description = "Through motion detection using OpenPose, we intend to detect a set of exercises. To ensure that the exercise is suited for the user and that he is correctly performing the exercise."
    url = "#"
    button = "Click Me"
    icon = "icon-energy"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Vital signals monitoring"
    description = "The end-user is supposed to feel a familiar app, and so the initial learning curve must be low. This leads the user to use the app more frequently and become an active daily user."
    url = "#"
    button = "Why us?"
    icon = "icon-heart"
    img = "img_10.jpg"

#  [params.intro.video]
#    enable = true
#    title = "Watch the video"
#    icon = "icon-play2"
#    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "What we have done so far"
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "deployment-diagram.png"
      alt = "Image2"
      title = "Deployment Diagram"
      subtitle = "Design"

    [[params.work.row]]
      img = "project-calendar.png"
      alt = "Image2"
      title = "Project Calendar"
      subtitle = "Planning"

    [[params.work.row]]
      img = "technology-architecture.png"
      alt = "Image3"
      title = "Technology Architecture"
      subtitle = "Design"

    [[params.work.row]]
      img = "use-case-model.png"
      alt = "Image4"
      title = "Use Case Model"
      subtitle = "Design"

  # # Testimonials section
  # [params.testimonials]
  #   enable = true
  #   title = "Testimonials"
  #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  #   [[params.testimonials.item]]
  #     quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
  #     person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #     img = "person1.jpg"
  #     alt = "Person1"

  #   [[params.testimonials.item]]
  #     quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
  #     person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #     img = "person2.jpg"
  #     alt = "Person2"

  #   [[params.testimonials.item]]
  #     quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
  #     person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #     img = "person3.jpg"
  #     alt = "Person3"
    
  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "A brief description of the services we plan to implement."

    [[params.services.item]]
      title = "Open Pose"
      description = "Investigate and learn how to use the software. Implement a simpler use case of OpenPose."
      icon = "icon-people"

    [[params.services.item]]
      title = "Computer Vision ML"
      description = "Search and analyse for ml and pattern recognition tools. Search for a dataset of foods and respective properties (protein,calories,carbohydrates)."
      icon = "icon-cursor"

    [[params.services.item]]
      title = "Frontend"
      description = "Design and develop an interface for the mobile application. Design and develop an interface for the web applications."
      icon = "icon-frame"

      [[params.services.item]]
      title = "Backend"
      description = "Database and business logic system with Django."      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Some information about our team."

    [[params.about.item]]
      name = "Tomás Costa"
      position = "Lead Developer"
      # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "tomas-costa.png"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Vasco Ramos"
      position = "Team Manager"
      # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "vasco-ramos.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "João Vasconcelos"
      position = "Product Owner"
      # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "joao-vasconcelos.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#<br><br>"]
      ]      

    [[params.about.item]]
      name = "João Marques"
      position = "DevOps Master"
      # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "joao-marques.png"
      alt = "Person3"
      social = [
        ["icon-info", "https://jmarques.icu"],
        ["icon-social-github", "https://github.com/joao-p-marques"],
        ["icon-linkedin", "https://www.linkedin.com/in/jo%c3%a3o-marques-62480119a/"]
      ]      

    [[params.about.item]]
      name = "Tiago Mendes"
      position = "Architectural Expert"
      # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "tiago-mendes.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

    [[params.about.item]]
      name = "Annoying Boss"
      position = "Confident Manager"
      # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "vasco-ramos.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = false
    map = false
    form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        # ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        # ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://my-life-ua.gitlab.io/" target="_blank">HomePage</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
